# Generated by Django 2.1.5 on 2019-02-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
    ]
