# Generated by Django 2.1.5 on 2019-03-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='fund_id',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
    ]
