version: '3'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    ports:
      - "8001:8000"
    volumes:
      - ./data:/data
  nginx_proxy:
    build:
      context: ./nginx_proxy
      dockerfile: Dockerfile
    image: nginx_proxy:latest
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - 8002:8080
