version: '3'
services:
  nginx_proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "9527:9527"
    volumes:
      - ./nginx_proxy/nginx_proxy.local.conf:/etc/nginx/conf.d/default.conf:ro
