# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashAndBackupAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('money', models.FloatField(default=0)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('money', models.FloatField(default=0)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[(b'accident', b'Accident insurance'), (b'health', b'Illness insurance'), (b'lifespan', b'Illness insurance'), (b'property', b'Property insurance'), (b'academic', b'Academic insurance'), (b'pension', b'Pension'), (b'vehicle', b'car, trucks insurance etc.')], default=b'accident', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('money', models.FloatField(default=0)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Outgoing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('money', models.FloatField(default=0)),
                ('comments', models.TextField()),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MonthlyReport')),
            ],
        ),
        migrations.AddField(
            model_name='investmentaccount',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MonthlyReport'),
        ),
        migrations.AddField(
            model_name='insuranceaccount',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MonthlyReport'),
        ),
        migrations.AddField(
            model_name='income',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MonthlyReport'),
        ),
        migrations.AddField(
            model_name='cashandbackupaccount',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MonthlyReport'),
        ),
    ]
