# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('income', models.IntegerField(default=0)),
                ('outcome', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.MonthReport'),
        ),
    ]
