# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashAndBackupAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, auto_now_add=True)),
                ('cash', models.FloatField(default=0)),
                ('backup', models.FloatField(default=0)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[(b'accident', b'Accident insurance'), (b'health', b'Illness insurance'), (b'lifespan', b'Illness insurance'), (b'property', b'Property insurance'), (b'academic', b'Academic insurance'), (b'pension', b'Pension'), (b'vehicle', b'car, trucks insurance etc.')], default=b'accident', max_length=10)),
                ('premium', models.FloatField(default=0)),
                ('insured_amount', models.FloatField(default=0)),
                ('total_input', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[(b'funds', b'Funds'), (b'insurance', b'Insurance'), (b'stock', b'Stock'), (b'p2p', b'P2P')], default=b'funds', max_length=10)),
                ('capital', models.FloatField(default=0)),
                ('current', models.FloatField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.InvestmentAccount')),
            ],
        ),
    ]
